version: "3.8"

services:
  github-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
